version: '3'
services:
  web:
    image: test/{{.name}}_web
    build: ./src
    volumes:
      - "./{{.name}}:/app"
    ports:
      - "{{.docker_web_port}}:8000"
    depends_on:
      - db
    env_file: ./docker/config/web.env
  db:
    image: mdillon/postgis:9.6
    ports:
      - "{{.docker_db_port}}:5432"
    volumes:
      - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
      - "./docker/files/shared:/shared:rw"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres